### PR TITLE
feat: add user custom globOptions

### PR DESCRIPTION
**Pull request by XinChou16**
the glob options could be customized

### CODE REVIEW

**Comment by bluwy** [comment]
Can you explain why this is needed? Some of Vite's config also accept glob patterns without configuration so I'm not sure this is needed here.

**Comment by XinChou16** [comment]
In mac os, some dot file like .DSStore file is matched by glob, which should not be handled

**Comment by bluwy** [comment]
Hmm good point. I guess we can hardcode and exclude that for now instead of a new option.

**Comment by XinChou16** [comment]
```sh
> vite dev --config config/vite.server.config.ts
ssr file len 73
  VITE v4.4.4  ready in 3021 ms
  ➜  Local:   https://localhost:5173/
  ➜  Network: https://192.168.30.5:5173/
Failed to warm up /Users/cv/xxxx/Pane/.DS_Store:
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

```

When use in svelte-kit project, the ssr files still can not warmup dot file, which make me confusing. May be vite not play well with ssr transform?

**Comment by bluwy** [comment]
Yeah Vite doesn't handle `.DS_Store` well. I was suggesting that we can ignore `.DS_Store` hardcoded for now if you'd like to submit the changes for it here. So we don't have to expose a new option.

**Comment by bluwy** [comment]
I've put some further thought into this, and I think it's best to leave it as-is. The glob options should be stricter to not include `.DS_Store`, otherwise there would be more issues down the line.

Maybe having `dot: false` by default would be the better alternative. Most files in dot files are ephemeral anyways so warming them up might not be too useful. Plus Vite can always crawl them manually.

I'm porting this plugin to Vite core and will start with `dot: false` instead, so closing this for now.

**Pull request closed without merging**
